# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tmarhs
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: fuckdima
service: slack-fuck-checker

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: slack/events
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000 